tensors = numpy arrays for gpus

In [1]:
from __future__ import print_function
import torch

In [5]:
?? torch.empty

In [3]:
x = torch.empty(5, 3)
x

tensor([[1.3563e-19, 1.8888e+31, 8.9066e-15],
        [1.8888e+31, 6.4639e-04, 6.8608e+22],
        [1.7753e+28, 2.0535e-19, 7.5563e+31],
        [1.8014e+25, 8.1335e+32, 7.2436e+22],
        [7.5554e+28, 2.9635e+29, 2.2087e+03]])

In [6]:
?? torch.rand

In [8]:
# returns random nums between 0 and 1
x = torch.rand(5,3)
x

tensor([[0.5014, 0.6364, 0.8473],
        [0.1873, 0.1811, 0.8311],
        [0.5831, 0.7271, 0.8069],
        [0.1329, 0.3437, 0.1258],
        [0.5345, 0.2307, 0.9272]])

In [11]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [15]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [16]:
x = torch.tensor([5,3])
x

tensor([5, 3])

In [23]:
x = x.new_ones(5,3, dtype = torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [31]:
x = torch.randn_like(x, dtype = torch.float)
x

tensor([[-1.6962,  0.2419, -0.5368],
        [ 0.8000, -0.0573, -0.2772],
        [ 1.0708, -1.3663,  0.0852],
        [-0.8711, -0.0486, -0.8822],
        [ 0.3769,  1.6782, -0.4775]])

In [27]:
y = torch.rand(5,3)
y

tensor([[0.3248, 0.9031, 0.3957],
        [0.7704, 0.3799, 0.4013],
        [0.7889, 0.4943, 0.8653],
        [0.7789, 0.8779, 0.8594],
        [0.0692, 0.0378, 0.3442]])

In [32]:
x + y

tensor([[-1.3714,  1.1450, -0.1411],
        [ 1.5704,  0.3226,  0.1241],
        [ 1.8597, -0.8720,  0.9505],
        [-0.0923,  0.8293, -0.0228],
        [ 0.4461,  1.7160, -0.1333]])

In [33]:
torch.add(x,y)

tensor([[-1.3714,  1.1450, -0.1411],
        [ 1.5704,  0.3226,  0.1241],
        [ 1.8597, -0.8720,  0.9505],
        [-0.0923,  0.8293, -0.0228],
        [ 0.4461,  1.7160, -0.1333]])

In [36]:
result = torch.empty(5,3)
torch.add(x,y, out = result)
result

tensor([[-1.3714,  1.1450, -0.1411],
        [ 1.5704,  0.3226,  0.1241],
        [ 1.8597, -0.8720,  0.9505],
        [-0.0923,  0.8293, -0.0228],
        [ 0.4461,  1.7160, -0.1333]])

any op that mutates in place will be suffixed w _ (add_)

In [37]:
y.add_(x)
y

tensor([[-1.3714,  1.1450, -0.1411],
        [ 1.5704,  0.3226,  0.1241],
        [ 1.8597, -0.8720,  0.9505],
        [-0.0923,  0.8293, -0.0228],
        [ 0.4461,  1.7160, -0.1333]])

In [39]:
x

tensor([[-1.6962,  0.2419, -0.5368],
        [ 0.8000, -0.0573, -0.2772],
        [ 1.0708, -1.3663,  0.0852],
        [-0.8711, -0.0486, -0.8822],
        [ 0.3769,  1.6782, -0.4775]])

In [43]:
x[:,0]

tensor([-1.6962,  0.8000,  1.0708, -0.8711,  0.3769])

In [38]:
x[:,1]

tensor([ 0.2419, -0.0573, -1.3663, -0.0486,  1.6782])

In [44]:
x[:,2]

tensor([-0.5368, -0.2772,  0.0852, -0.8822, -0.4775])

In [40]:
x[1:]

tensor([[ 0.8000, -0.0573, -0.2772],
        [ 1.0708, -1.3663,  0.0852],
        [-0.8711, -0.0486, -0.8822],
        [ 0.3769,  1.6782, -0.4775]])

In [41]:
x[:1]

tensor([[-1.6962,  0.2419, -0.5368]])

In [42]:
x[1,:]

tensor([ 0.8000, -0.0573, -0.2772])

In [45]:
x[2,:]

tensor([ 1.0708, -1.3663,  0.0852])

In [46]:
x[,1:]

SyntaxError: invalid syntax (<ipython-input-46-8c41899102af>, line 1)

### Reshaping

In [48]:
x = torch.rand(4,4)
x

tensor([[0.6666, 0.6806, 0.8464, 0.8488],
        [0.8205, 0.3981, 0.6312, 0.5438],
        [0.3901, 0.0912, 0.2907, 0.3058],
        [0.9608, 0.0588, 0.9663, 0.2486]])

In [50]:
y = x.view(16)
y

tensor([0.6666, 0.6806, 0.8464, 0.8488, 0.8205, 0.3981, 0.6312, 0.5438, 0.3901,
        0.0912, 0.2907, 0.3058, 0.9608, 0.0588, 0.9663, 0.2486])

In [55]:
y = x.view(-1)
y

tensor([0.6666, 0.6806, 0.8464, 0.8488, 0.8205, 0.3981, 0.6312, 0.5438, 0.3901,
        0.0912, 0.2907, 0.3058, 0.9608, 0.0588, 0.9663, 0.2486])

In [53]:
z = x.view(2,8)
z

tensor([[0.6666, 0.6806, 0.8464, 0.8488, 0.8205, 0.3981, 0.6312, 0.5438],
        [0.3901, 0.0912, 0.2907, 0.3058, 0.9608, 0.0588, 0.9663, 0.2486]])

In [54]:
z = x.view(-1,8)
z

tensor([[0.6666, 0.6806, 0.8464, 0.8488, 0.8205, 0.3981, 0.6312, 0.5438],
        [0.3901, 0.0912, 0.2907, 0.3058, 0.9608, 0.0588, 0.9663, 0.2486]])

In [57]:
z = x.view(-1,2)
z

tensor([[0.6666, 0.6806],
        [0.8464, 0.8488],
        [0.8205, 0.3981],
        [0.6312, 0.5438],
        [0.3901, 0.0912],
        [0.2907, 0.3058],
        [0.9608, 0.0588],
        [0.9663, 0.2486]])

In [59]:
z = x.view(-1,1)
z

tensor([[0.6666],
        [0.6806],
        [0.8464],
        [0.8488],
        [0.8205],
        [0.3981],
        [0.6312],
        [0.5438],
        [0.3901],
        [0.0912],
        [0.2907],
        [0.3058],
        [0.9608],
        [0.0588],
        [0.9663],
        [0.2486]])

## Convert to python num

In [65]:
x = torch.rand(1)
x

tensor([0.3527])

In [66]:
x = x.item()
x

0.35272395610809326

### Torch tensor to numpy array

In [67]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [68]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

Changing the tensor also changes the numpy array

In [69]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [70]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [71]:
a = a + 1
a

tensor([3., 3., 3., 3., 3.])

In [72]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

### Numpy array to torch tensor

In [76]:
import numpy as np
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [77]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [80]:
x = np.empty(5)
np.add(a,1, out=x)
x

array([2., 2., 2., 2., 2.])

In [82]:
a

array([1., 1., 1., 1., 1.])

In [83]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [84]:
np.add(a,1, out=a)
a

array([2., 2., 2., 2., 2.])

In [85]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

## Using CUDA

In [89]:
if torch.cuda.is_available():
    print('cuda is avaliable')
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else : print('cuda is not avaliable :(')

cuda is not avaliable :(


## Autograd = automatic differentiation

In [116]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [117]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [110]:
y.grad_fn

In [118]:
z = y * y *3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [119]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [97]:
a = torch.randn(2,2)
a

tensor([[-0.2024, -0.6610],
        [ 1.2179, -0.2190]])

In [98]:
a = a+9
a

tensor([[ 8.7976,  8.3390],
        [10.2179,  8.7810]])

In [99]:
a.requires_grad

False

In [100]:
a.requires_grad_(True)

tensor([[ 8.7976,  8.3390],
        [10.2179,  8.7810]], requires_grad=True)

In [101]:
b = a+2
b

tensor([[10.7976, 10.3390],
        [12.2179, 10.7810]], grad_fn=<AddBackward0>)

In [102]:
a = a-8
a

tensor([[0.7976, 0.3390],
        [2.2179, 0.7810]], grad_fn=<SubBackward0>)

In [120]:
out.backward()

In [121]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [122]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [123]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [146]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.3928, -0.3817,  1.1231], requires_grad=True)

In [147]:
y =x *2
y

tensor([ 0.7856, -0.7633,  2.2462], grad_fn=<MulBackward0>)

In [149]:
y.data.norm()

tensor(2.4990)

In [150]:
while(y.data.norm()<1000):
    y = y *2
y

tensor([ 402.2121, -390.8140, 1150.0537], grad_fn=<MulBackward0>)

In [152]:
# throws error
# y.backward()

In [154]:
v = torch.tensor([1,1,1], dtype = torch.float)
y.backward(v)

In [155]:
x.grad

tensor([1024., 1024., 1024.])

## NN from scratch

In [157]:
import torch.nn as nn
import torch.functional as F


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        